### ISSUE TITLE
[packagist] laravel-validation-rules/credit-card

### ISSUE THREAD

**Issue by DarkaOnLine** [laravel-validation-rules/readme#5]
1.0 released

**Comment by ssx** [comment]
👍🏼👏🏼

**Comment by DarkaOnLine** [comment]
@ssx will you register package in the packagist?

**Comment by ssx** [comment]
On my todo list for this morning, in around an hour 🙂

**Comment by ssx** [comment]
Done! https://packagist.org/packages/laravel-validation-rules/credit-card

**Comment by ssx** [comment]
Had to tidy up composer.json a little and retagged a version to trigger auto push test to packagist. All working well now, and further tags you make will go directly to packagist. 😎
