### ISSUE TITLE
[new] subdomain

### ISSUE THREAD

**Issue by clarkeash** [laravel-validation-rules/readme#8]
I want to add a rule to validate a subdomain for a multi-tenant application against a list of reserved subdomains.

So I can register `clarkeash.myapp.com` but I cant register `mail.myapp.com` etc

**Comment by ssx** [comment]
I’ll get that added today Ash 😊 great rule!

**Comment by ssx** [comment]
Repo added and you invited.

**Comment by clarkeash** [comment]
Thanks 😄
