### ISSUE TITLE
[new] Laravel Mailgun Email Validation

### ISSUE THREAD

**Issue by TheoKouzelis** [laravel-validation-rules/readme#9]
Hi,

Saw this collection being promoted at Laravel Manchester and thought maybe it might be a good fit for this validation rule I have written. But maybe my validation rule is to specific to a third party.

Here is a link to the current package https://github.com/TheoKouzelis/laravel-mailgun-email-validation

**Comment by ssx** [comment]
that looks a great fit, I'll ping over some details at the weekend and we'll get it included!

**Comment by ssx** [comment]
Added to https://github.com/laravel-validation-rules/email-validation-mailgun/settings/collaboration - it'll be best to go for a meta-package approach, the same as:

https://github.com/laravel-validation-rules/exposed-password/blob/master/composer.json

After you're setup, stick a PR in for the site too with your package added.

**Comment by TheoKouzelis** [comment]
Thanks @ssx,

That is all done. Let me know of you need anything else. Will you add the meta package to Packagist?  I tried, but got an error saying I didn't own the namespace.

**Comment by ssx** [comment]
Will do it first thing.

**Comment by ssx** [comment]
Packagist repo created and you're a collab. Thanks again Theo! 👍

**Comment by TheoKouzelis** [comment]
Awesome thanks
